[pytest]
testpaths =
    backend/tests
    frontend/tests
pythonpath =
    backend
addopts = -v --color=yes --tb=short --cov=backend/app --cov-report=term-missing --cov-report=html --cov-report=xml --cov-branch --html=report.html --self-contained-html
norecursedirs = .git .github venv env __pycache__ frontend/dist htmlcov
