sonar.projectKey=daniarango378_todoapp
sonar.organization=cicd-entrega2

sonar.sources=backend/app,frontend,run.py
sonar.tests=backend/tests,frontend/tests,tests

sonar.exclusions=**/tests/**,frontend/dist/**,**/__pycache__/**,**/runtime-config.js
sonar.coverage.exclusions=frontend/**,run.py,backend/app/main.py

sonar.python.version=3.12
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt
sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300